{
  "hash": "647edad5964afad53cd57f71c0390693",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Logistic Regression\"\ntitle-slide-attributes:\n  data-background-image: images/lake.jpg\n  data-background-size: contain\n  data-background-opacity: \"0.5\"\nsubtitle: \"STAT 220\"\nauthor: \"Bastola\"\nformat:\n  revealjs: \n    theme: [default, scss/main.scss]\n    slide_level: 2\n    slide-number: true\n    preview-links: auto\n    history: true\n    chalkboard: true\n    transition: slide\n    background-transition: fade    \n    touch: false\n    controls: true\nfilters:\n  - shinylive\n  - webr\n---\n\n\n\n\n\n\n\n\n## Classification using simple logistic regression\n\n::: cle\n\n- [Goal:]{.bold-blue} Understand why logistic regression is used for categorical outcomes.\n- [Context:]{.bold-blue} Traditional linear regression is limited to continuous outcomes.\n- [Solution:]{.bold-blue} Logistic regression models the probability of a categorical outcome.\n\n:::\n\n\n## Why Not Linear Regression?\n\n::: cle\n\n- [Issue with categorical outcomes:]{.bold-green} Predictions can fall outside the $[0,1]$ range.\n- [Consequence:]{.bold-green} Nonsensical probability predictions for binary outcomes $(Y=0\\text{ or }Y=1)$).\n\n:::\n\n\n## Introduction to Logistic Regression\n\n::: cle\n\n- [Solution:]{.bold-blue} Transform the outcome into a format that linear regression can handle.\n- [Method:]{.bold-blue} Model the log odds of the probability of success versus failure.\n\n:::\n\n## From Probability to Odds\n\n::: cle\n::: font80\n\n- [Probability:]{.bold-blue} Chance of success ($Y=1$) over total possibilities.\n$$P(Y=1)=\\frac{\\text { number of successes }}{\\text { total trials }}$$\n- [Odds:]{.bold-blue} Ratio of the probability of success to the probability of failure.\n$$Odds =\\frac{P(Y=1)}{1-P(Y=1)}$$\n:::\n:::\n\n## Logit Transformation\n\n::: cle\n::: font90\n\n- [Goal:]{.bold-blue} Convert odds to a continuous scale that can span negative to positive infinity.\n- [Logit Function:]{.bold-blue} Natural logarithm of the odds.\n$$\\log \\left(\\frac{P(Y=1)}{1-P(Y=1)}\\right)$$\n- Why? Makes it possible to use linear regression techniques.\n\n:::\n:::\n\n##\n\n::: cle\n::: panel-tabset\n\n### LR \n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Day24_files/figure-revealjs/unnamed-chunk-1-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n\n\n### LR Summary\n\n\n::: font80\n- Binary response, $Y$,  with an explanatory (predictor, features) variables, $X_1$.\n- We model the probability that $Y$ belongs to a particular category.\n\n\n$$P(Y = 1 ) = \\frac{e^{\\beta_0 + \\beta_1X_1}}{1 + e^{\\beta_0 + \\beta_1X_1}}$$\n\n$$\\text{Odds} = \\frac{P(Y = 1 )}{1 - P(Y = 1 )} = e^{\\beta_0 + \\beta_1X_1}$$\n\n$$\\text{Log Odds} = \\beta_0 + \\beta_1X_1$$\n:::\n\n\n### Data Preparation\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n### Modeling\n\n\n\n::: {.cell}\n\n:::\n\n\n\n:::\n:::\n\n\n## Tidy the Summary\n\n::: zen\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)  -5.61     0.678       -8.28 1.20e-16\n2 glucose       0.0392   0.00514      7.62 2.55e-14\n```\n\n\n:::\n:::\n\n\n\n\n\n$$\\log \\left(\\frac{p}{1-p}\\right)=-5.61+0.0392 \\cdot \\text { glucose }$$\n\nWhere $p = P(Y = 1)$ is the probability of having diabetes \n\n\n:::\n\n::: middle-align-xy\n\n## Interpreting Coefficients: Log Odds\n\n::: vvt\n\n- Coefficient Meaning: Change in log odds of the outcome for a one-unit increase in the predictor.\n\n\nA coefficient of 0.0392 for glucose means...\n\n...a one-unit increase in glucose level increases the log odds of diabetes by 0.0392.\n\n:::\n:::\n\n## Exponentiating Coefficients: Odds Ratios\n\n::: vvt\n::: font80\n\n$$Odds = \\frac{probability}{1 - probability}$$\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)  0.00364   0.678       -8.28 1.20e-16\n2 glucose      1.04      0.00514      7.62 2.55e-14\n```\n\n\n:::\n:::\n\n\n\n\n\n$$\\text { Odds }=0.00364 \\times(1.04)^{\\text {glucose }}$$\n\n\nAn odds ratio of 1.04 means that for each additional unit of glucose, the odds of having diabetes increase by 4%.\n\n:::\n:::\n\n## Understanding Odds Ratios: Summary\n\n::: cle\n\n- [Transformation:]{.bold-blue} Turning log-odds coefficients into odds ratios.\n- [Odds Ratio $=e^{\\beta_i}$]{.bold-blue}\n- [Interpretation:]{.bold-blue} For each unit increase in the predictor, the odds multiply by the odds ratio.\n\n:::\n\n## Importance of Scaling and Centering\n\n```r\ndb_recipe <- recipe(diabetes ~ ., data = db_train) %>% \n  step_scale(all_numeric_predictors()) %>% \n  step_center(all_numeric_predictors()) %>%   \n  prep()\n```\n\n::: cle\n\n- Ensures all features contribute equally to model calculations.\n- Helps gradient descent algorithms converge more quickly.\n- Standardizes coefficient scales, improving model interpretability.\n\n:::\n\n::: centered-content\n\n## <i class=\"fa fa-pencil-square-o\" style=\"font-size:48px;color:purple\"> Group Activity 1</i> {background=\"#ffdf9e\"}\n\n::: row\n::: left\n![](https://media.giphy.com/media/RKApDdwsQ6jkwd6RNn/giphy.gif)\n:::\n\n::: right\n\n<br>\n\n::: lqt\n\n- Please clone the `ca24-yourusername` repository from  [Github](https://github.com/DataScienceSpring24)\n- Please do problem 1 in the class activity for today\n:::\n:::\n:::\n\n`<div class=\"countdown\" id=\"timer_d8a36784\" data-update-every=\"1\" tabindex=\"0\" style=\"top:0;left:0;padding:3px 4px;font-size:1em;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">10</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">00</span></code>\n</div>`{=html}\n:::\n\n\n## Threshold for classification\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Day24_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n\n\n## Class Prediction\n\n::: eqt\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Day24_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=50%}\n:::\n:::\n\n\n\n\n:::\n\n## [Class Probabilities with `threshold = 0.30`]{.font80}\n\n::: eqt\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n    diabetes glucose .pred_neg  .pred_pos .pred_class\n25       pos     143 0.5040090 0.49599103         neg\n52       neg     101 0.8402912 0.15970881         neg\n60       neg     105 0.8181391 0.18186086         neg\n64       neg     141 0.5235673 0.47643271         neg\n69       neg      95 0.8693592 0.13064080         neg\n83       neg      83 0.9141287 0.08587128         neg\n98       neg      71 0.9445349 0.05546507         neg\n110      pos      95 0.8693592 0.13064080         neg\n135      neg      96 0.8648480 0.13515203         neg\n143      neg     108 0.8000067 0.19999330         neg\n```\n\n\n:::\n:::\n\n\n\n:::\n\n## Custom Metrics\n\n::: eqt\n::: row\n::: left\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Day24_files/figure-revealjs/unnamed-chunk-10-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n:::\n\n::: right\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  .metric     .estimator .estimate\n  <chr>       <chr>          <dbl>\n1 accuracy    binary         0.823\n2 sensitivity binary         0.982\n3 specificity binary         0.409\n4 ppv         binary         0.812\n```\n\n\n:::\n:::\n\n\n\n:::\n:::\n:::\n\n## [Class Probabilities with `threshold = 0.70`]{.font80}\n\n::: eqt\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n    diabetes glucose .pred_neg  .pred_pos .pred_class\n25       pos     143 0.5040090 0.49599103         pos\n52       neg     101 0.8402912 0.15970881         neg\n60       neg     105 0.8181391 0.18186086         neg\n64       neg     141 0.5235673 0.47643271         pos\n69       neg      95 0.8693592 0.13064080         neg\n83       neg      83 0.9141287 0.08587128         neg\n98       neg      71 0.9445349 0.05546507         neg\n110      pos      95 0.8693592 0.13064080         neg\n135      neg      96 0.8648480 0.13515203         neg\n143      neg     108 0.8000067 0.19999330         neg\n```\n\n\n:::\n:::\n\n\n\n:::\n\n## Custom Metrics\n\n::: eqt\n::: row\n::: left\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Day24_files/figure-revealjs/unnamed-chunk-14-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n:::\n\n::: right\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  .metric     .estimator .estimate\n  <chr>       <chr>          <dbl>\n1 accuracy    binary         0.785\n2 sensitivity binary         0.754\n3 specificity binary         0.864\n4 ppv         binary         0.935\n```\n\n\n:::\n:::\n\n\n\n\n:::\n:::\n:::\n\n##\n\n::: panel-tabset\n\n### ROC Curve\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day24_files/figure-revealjs/unnamed-chunk-16-1.png){width=960}\n:::\n:::\n\n\n\n\n\n### Code\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n:::\n\n\n## Exact Optimal Threshold {auto-animate=\"true\"}\n\n::: scroll-box-20\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 58 × 3\n   .threshold specificity sensitivity\n        <dbl>       <dbl>       <dbl>\n 1   -Inf          0                1\n 2      0.106      0                1\n 3      0.113      0.0455           1\n 4      0.154      0.0909           1\n 5      0.159      0.182            1\n 6      0.187      0.227            1\n 7      0.193      0.273            1\n 8      0.199      0.318            1\n 9      0.218      0.364            1\n10      0.239      0.409            1\n# ℹ 48 more rows\n```\n\n\n:::\n:::\n\n\n:::\n\n\n## Exact Optimal Threshold {auto-animate=\"true\"}\n\n::: scroll-box-20\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 58 × 3\n   .threshold specificity sensitivity\n        <dbl>       <dbl>       <dbl>\n 1      0.706       0.864       0.754\n 2      0.698       0.864       0.772\n 3      0.690       0.864       0.807\n 4      0.681       0.864       0.825\n 5      0.714       0.909       0.754\n 6      0.738       0.909       0.737\n 7      0.745       0.909       0.719\n 8      0.760       0.909       0.702\n 9      0.767       0.909       0.684\n10      0.774       0.909       0.667\n# ℹ 48 more rows\n```\n\n\n:::\n:::\n\n\n:::\n\n\n\n## Exact Optimal Threshold {auto-animate=\"true\"}\n\n::: scroll-box-20\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .threshold specificity sensitivity\n       <dbl>       <dbl>       <dbl>\n1      0.706       0.864       0.754\n```\n\n\n:::\n:::\n\n\n:::\n\n\n\n\n::: centered-content\n\n## <i class=\"fa fa-pencil-square-o\" style=\"font-size:48px;color:purple\"> Group Activity 2</i> {background=\"#ffdf9e\"}\n\n::: row\n::: left\n![](https://media.giphy.com/media/RKApDdwsQ6jkwd6RNn/giphy.gif)\n:::\n\n::: right\n\n<br>\n<br>\n\n::: lqt\n\n- Please finish the remaining problems in the class activity for today\n\n:::\n:::\n:::\n\n`<div class=\"countdown\" id=\"timer_a6f5327c\" data-update-every=\"1\" tabindex=\"0\" style=\"top:0;left:0;padding:3px 4px;font-size:1em;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">10</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">00</span></code>\n</div>`{=html}\n:::\n\n",
    "supporting": [
      "Day24_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"Day24_files/libs/countdown-0.4.0/countdown.css\" rel=\"stylesheet\" />\n<script src=\"Day24_files/libs/countdown-0.4.0/countdown.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}