---
title: "Homework 4"
output: pdf_document
---

## Name: Put your name here

## I worked with: 

**Click the "Knit" button in RStudio to knit this file to a pdf.**

--------------------------------------------

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, collapse = TRUE, 
                      warning = FALSE, message = FALSE)
# add packages here 
library(dplyr)
library(tidyr)
library(readr)
library(forcats)
library(lubridate)
```

## Problem 1: flights



### a. 

*answer:* write your answer here

```{r}
# put your code here
```

### b. 

*answer:* write your answer here

```{r}
# put your code here
```

### c. 

*answer:* write your answer here

```{r}
# put your code here
```



------------------------------------------------


## Problem 2: top destinations

### a. 

*answer:* 

```{r}
# put your code here
```

### b. 

*answer:* write your answer here

```{r}
# put your code here
```


------------------------------------------------




## Problem 2: Energy

```{r}
energy <- readr::read_csv("https://raw.githubusercontent.com/deepbas/statdatasets/main/energy.csv",
                    col_type = cols(
                     .default = col_double(), 
                      Timestamp = col_datetime(format = ""),
                      dayWeek = col_factor(levels=c("Mon","Tues","Wed","Thurs","Fri","Sat","Sun"))
                     ))
dim(energy)
```


### a. 

*answer:* write your answer here

```{r}
# put your code here
```

### b. 

*answer:* write your answer here

```{r}
# put your code here
```

### c. 

*answer:* write your answer here

```{r}
# put your code here
```


### d. 

*answer:* write your answer here

```{r}
# put your code here
```

### e. 

*answer:* write your answer here

```{r}
# put your code here
```



------------------------------------------------



## Problem 4: UN votes



```{r}
unvotes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-23/unvotes.csv')
roll_calls <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-23/roll_calls.csv')
issues <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-23/issues.csv')
```

```{r}
# Merge data frames
merged_data <- unvotes %>%
  left_join(roll_calls, by = "rcid", multiple = "all") %>%
  left_join(issues, by = "rcid", multiple = "all") %>% 
  tidyr::drop_na(country, country_code, vote, issue, date) %>% 
  mutate(vote = factor(vote))
```



### a. 

*answer:* write your answer here

```{r}
# put your code here
```

### b. 

*answer:* write your answer here

```{r}
# put your code here
```

### c. 

*answer:* write your answer here

```{r}
# put your code here
```


### d. 

*answer:* write your answer here

```{r}
# put your code here
```

### e. 

*answer:* write your answer here

```{r}
# put your code here
```

